### ISSUE TITLE
Useage -> Usage

### ISSUE THREAD

**Issue by dlesnoff** [PhilippMDoerner/mapster#20]
In the documentation, I can see the spelling mistake: `useage`. It should be written `usage`.
It occurs [here](https://github.com/PhilippMDoerner/mapster/blob/main/docs/book/basicUseage.nim) and at multiple places.

Please note that I am a non-native English Speaker.

**Comment by PhilippMDoerner** [comment]
It's likely to occur all over the place. Useage vs. Usage is a common mistake I make **all** the damn time because I can't recall for the life of me which of the two was correct.
Thanks for pointing it out, I'll fix it quickly.
